-- 002 — catalogue: genres, titles, full-text search.

DO $$ BEGIN
  CREATE TYPE title_type AS ENUM ('movie', 'series');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE title_status AS ENUM ('draft', 'uploading', 'processing', 'ready', 'published', 'failed', 'archived');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS genres (
  id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       text NOT NULL UNIQUE,
  slug       text NOT NULL UNIQUE,
  sort_order integer NOT NULL DEFAULT 100
);

CREATE TABLE IF NOT EXISTS titles (
  id                 uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  slug               text NOT NULL UNIQUE,
  title              text NOT NULL,
  synopsis           text NOT NULL DEFAULT '',
  type               title_type NOT NULL DEFAULT 'movie',
  status             title_status NOT NULL DEFAULT 'draft',
  release_year       integer CHECK (release_year BETWEEN 1888 AND 2100),
  runtime_seconds    integer NOT NULL DEFAULT 0 CHECK (runtime_seconds >= 0),
  maturity_rating    text NOT NULL DEFAULT 'U/A 13+',
  language           text NOT NULL DEFAULT 'en',
  country            text,
  director           text,
  cast_members       text[] NOT NULL DEFAULT '{}',
  tags               text[] NOT NULL DEFAULT '{}',
  poster_url         text,
  backdrop_url       text,
  trailer_url        text,
  -- Storage key of the HLS master manifest produced by MediaConvert/ffmpeg.
  hls_key            text,
  -- Development convenience: lets Play work before anything has been uploaded.
  demo_manifest_url  text,
  popularity         numeric(7,2) NOT NULL DEFAULT 0,
  average_rating     numeric(3,1) NOT NULL DEFAULT 0 CHECK (average_rating BETWEEN 0 AND 10),
  is_featured        boolean NOT NULL DEFAULT false,
  published_at       timestamptz,
  created_by         uuid REFERENCES users (id) ON DELETE SET NULL,
  created_at         timestamptz NOT NULL DEFAULT now(),
  updated_at         timestamptz NOT NULL DEFAULT now(),
  -- Weighted search vector, maintained by Postgres itself (no trigger to forget).
  search_document    tsvector GENERATED ALWAYS AS (
                       setweight(to_tsvector('english', coalesce(title, '')), 'A') ||
                       setweight(to_tsvector('english', coalesce(director, '')), 'B') ||
                       setweight(to_tsvector('english', coalesce(synopsis, '')), 'C')
                     ) STORED,
  CONSTRAINT titles_slug_format CHECK (slug ~ '^[a-z0-9][a-z0-9-]{1,120}$')
);

CREATE INDEX IF NOT EXISTS titles_search_idx ON titles USING gin (search_document);
CREATE INDEX IF NOT EXISTS titles_title_trgm_idx ON titles USING gin (title gin_trgm_ops);
CREATE INDEX IF NOT EXISTS titles_published_idx ON titles (published_at DESC) WHERE status = 'published';
CREATE INDEX IF NOT EXISTS titles_status_idx ON titles (status, updated_at DESC);
CREATE INDEX IF NOT EXISTS titles_popularity_idx ON titles (popularity DESC) WHERE status = 'published';
CREATE INDEX IF NOT EXISTS titles_type_year_idx ON titles (type, release_year DESC);
CREATE INDEX IF NOT EXISTS titles_tags_idx ON titles USING gin (tags);

DROP TRIGGER IF EXISTS titles_set_updated_at ON titles;
CREATE TRIGGER titles_set_updated_at BEFORE UPDATE ON titles
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE IF NOT EXISTS title_genres (
  title_id uuid NOT NULL REFERENCES titles (id) ON DELETE CASCADE,
  genre_id integer NOT NULL REFERENCES genres (id) ON DELETE CASCADE,
  PRIMARY KEY (title_id, genre_id)
);

CREATE INDEX IF NOT EXISTS title_genres_genre_idx ON title_genres (genre_id);
