-- 005 — engagement and audit trail.

CREATE TABLE IF NOT EXISTS my_list (
  user_id    uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  title_id   uuid NOT NULL REFERENCES titles (id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, title_id)
);

CREATE INDEX IF NOT EXISTS my_list_user_idx ON my_list (user_id, created_at DESC);

-- Who did what, kept in Postgres because auditors ask for it and CloudWatch logs expire.
CREATE TABLE IF NOT EXISTS audit_logs (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_id    uuid REFERENCES users (id) ON DELETE SET NULL,
  action      text NOT NULL,
  entity_type text,
  entity_id   text,
  metadata    jsonb NOT NULL DEFAULT '{}'::jsonb,
  ip          inet,
  created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS audit_logs_created_idx ON audit_logs (created_at DESC);
CREATE INDEX IF NOT EXISTS audit_logs_actor_idx ON audit_logs (actor_id, created_at DESC);
CREATE INDEX IF NOT EXISTS audit_logs_entity_idx ON audit_logs (entity_type, entity_id);

-- Aggregate the admin dashboard reads on every load. A view keeps the SQL in one place;
-- if it ever gets slow it becomes a materialised view refreshed by the worker.
CREATE OR REPLACE VIEW admin_catalogue_stats AS
SELECT
  count(*)                                                       AS total_titles,
  count(*) FILTER (WHERE status = 'published')                    AS published_titles,
  count(*) FILTER (WHERE status IN ('processing', 'uploading'))    AS processing_titles,
  count(*) FILTER (WHERE status = 'draft')                        AS draft_titles,
  count(*) FILTER (WHERE status = 'failed')                       AS failed_titles,
  coalesce(sum(runtime_seconds), 0)                               AS total_runtime_seconds
FROM titles;

CREATE OR REPLACE VIEW admin_revenue_stats AS
SELECT
  count(DISTINCT s.user_id) FILTER (WHERE s.status IN ('active', 'trialing')) AS active_subscribers,
  coalesce(sum(p.price_cents) FILTER (WHERE s.status IN ('active', 'trialing')), 0) AS mrr_cents
FROM subscriptions s
JOIN plans p ON p.id = s.plan_id;
