/**
 * Seed content. Titles are fictional so the catalogue can ship with the repo.
 * Artwork uses picsum.photos with a stable seed per title; the UI falls back to a
 * generated typographic poster when an image cannot be fetched.
 */

export const plans = [
  {
    code: 'mobile',
    name: 'Mobile',
    description: 'One phone or tablet at a time, up to 480p.',
    priceCents: 14900,
    maxStreams: 1,
    maxQuality: '480p',
    sortOrder: 10,
    features: ['One screen at a time', 'Phones and tablets', 'Cancel whenever you like'],
  },
  {
    code: 'standard',
    name: 'Standard',
    description: 'Two screens at once in full HD.',
    priceCents: 49900,
    maxStreams: 2,
    maxQuality: '1080p',
    sortOrder: 20,
    features: ['Two screens at once', 'Full HD (1080p)', 'Downloads on two devices', 'Cancel whenever you like'],
  },
  {
    code: 'premium',
    name: 'Premium',
    description: 'Four screens at once, up to 4K, spatial audio.',
    priceCents: 79900,
    maxStreams: 4,
    maxQuality: '4k',
    sortOrder: 30,
    features: ['Four screens at once', '4K and HDR', 'Spatial audio', 'Downloads on six devices'],
  },
];

export const genres = [
  { name: 'Action', slug: 'action', sortOrder: 10 },
  { name: 'Thriller', slug: 'thriller', sortOrder: 20 },
  { name: 'Drama', slug: 'drama', sortOrder: 30 },
  { name: 'Science Fiction', slug: 'science-fiction', sortOrder: 40 },
  { name: 'Comedy', slug: 'comedy', sortOrder: 50 },
  { name: 'Crime', slug: 'crime', sortOrder: 60 },
  { name: 'Documentary', slug: 'documentary', sortOrder: 70 },
  { name: 'Horror', slug: 'horror', sortOrder: 80 },
  { name: 'Romance', slug: 'romance', sortOrder: 90 },
  { name: 'Family', slug: 'family', sortOrder: 100 },
];

export const titles = [
  {
    slug: 'monsoon-signal',
    title: 'Monsoon Signal',
    synopsis:
      'A radio astronomer in Pune picks up a repeating pulse that arrives only during rainfall. Proving it is not noise costs her the observatory, her marriage and eventually her certainty.',
    type: 'movie',
    releaseYear: 2024,
    runtimeMinutes: 128,
    maturityRating: 'U/A 13+',
    language: 'hi',
    country: 'IN',
    director: 'Ira Deshmukh',
    cast: ['Meera Rao', 'Anand Kulkarni', 'Rehana Qureshi'],
    tags: ['first contact', 'slow burn', 'monsoon'],
    genres: ['science-fiction', 'drama'],
    popularity: 982.4,
    rating: 8.4,
    featured: true,
  },
  {
    slug: 'the-last-transmission',
    title: 'The Last Transmission',
    synopsis:
      'The final crew of a decommissioned deep-space relay have eleven days to shut it down. On day three, the relay starts answering questions nobody asked.',
    type: 'movie',
    releaseYear: 2023,
    runtimeMinutes: 116,
    maturityRating: 'U/A 16+',
    language: 'en',
    country: 'CA',
    director: 'Yusuf Adeyemi',
    cast: ['Dana Whitlock', 'Priyan Menon', 'Ola Bergstrom'],
    tags: ['space', 'isolation', 'mystery'],
    genres: ['science-fiction', 'thriller'],
    popularity: 874.1,
    rating: 7.9,
    featured: false,
  },
  {
    slug: 'nightshift',
    title: 'Nightshift',
    synopsis:
      'A tow-truck driver working Bengaluru between midnight and six discovers the same black sedan at three unrelated crime scenes.',
    type: 'movie',
    releaseYear: 2025,
    runtimeMinutes: 104,
    maturityRating: 'A',
    language: 'kn',
    country: 'IN',
    director: 'Shalini Bhat',
    cast: ['Vikram Iyer', 'Fatima Sheikh', 'Joseph Dsouza'],
    tags: ['neo noir', 'one night', 'cars'],
    genres: ['crime', 'thriller'],
    popularity: 1210.6,
    rating: 8.1,
    featured: true,
  },
  {
    slug: 'paper-lanterns',
    title: 'Paper Lanterns',
    synopsis:
      'Two strangers agree to meet at the same river festival every year until one of them stops coming. A quiet film about the arithmetic of long distance.',
    type: 'movie',
    releaseYear: 2022,
    runtimeMinutes: 97,
    maturityRating: 'U',
    language: 'ja',
    country: 'JP',
    director: 'Haruka Onishi',
    cast: ['Ren Takahashi', 'Mei Sato'],
    tags: ['festival', 'letters', 'quiet'],
    genres: ['romance', 'drama'],
    popularity: 512.3,
    rating: 8.0,
    featured: false,
  },
  {
    slug: 'concrete-orchids',
    title: 'Concrete Orchids',
    synopsis:
      'A city planner and a flower smuggler share one warehouse and two very different ideas about what should grow there. Eight episodes.',
    type: 'series',
    releaseYear: 2024,
    runtimeMinutes: 47,
    maturityRating: 'U/A 16+',
    language: 'en',
    country: 'SG',
    director: 'Lena Chua',
    cast: ['Marcus Tan', 'Aisyah Rahman', 'Peter Goh', 'Nadia Lim'],
    tags: ['limited series', 'urban', 'greenhouse'],
    genres: ['crime', 'drama'],
    popularity: 1421.9,
    rating: 8.6,
    featured: true,
  },
  {
    slug: 'departure-lounge',
    title: 'Departure Lounge',
    synopsis:
      'Six passengers, one grounded flight and a security officer who is certain that exactly one of them is lying about why they are travelling.',
    type: 'movie',
    releaseYear: 2023,
    runtimeMinutes: 111,
    maturityRating: 'U/A 13+',
    language: 'en',
    country: 'GB',
    director: 'Colm Ferris',
    cast: ['Ruth Alderney', 'Sam Oyelaran', 'Vera Novak'],
    tags: ['single location', 'ensemble', 'whodunit'],
    genres: ['thriller', 'drama'],
    popularity: 733.5,
    rating: 7.4,
    featured: false,
  },
  {
    slug: 'salt-flats',
    title: 'Salt Flats',
    synopsis:
      'A land-speed mechanic rebuilds her father’s car with the wrong engine, the wrong crew and eleven weeks before the lake floods.',
    type: 'movie',
    releaseYear: 2021,
    runtimeMinutes: 122,
    maturityRating: 'U/A 13+',
    language: 'en',
    country: 'US',
    director: 'Tessa Marlow',
    cast: ['Junie Hollis', 'Ray Cordero', 'Marge Pike'],
    tags: ['racing', 'grief', 'desert'],
    genres: ['drama', 'action'],
    popularity: 604.8,
    rating: 7.6,
    featured: false,
  },
  {
    slug: 'static-bloom',
    title: 'Static Bloom',
    synopsis:
      'The tenants of a converted radio factory begin hearing their own arguments played back one day late. Only the newest resident finds this useful.',
    type: 'movie',
    releaseYear: 2025,
    runtimeMinutes: 94,
    maturityRating: 'A',
    language: 'en',
    country: 'IE',
    director: 'Maeve Sullivan',
    cast: ['Orla Byrne', 'Declan Ross'],
    tags: ['haunted building', 'sound', 'slow dread'],
    genres: ['horror', 'thriller'],
    popularity: 688.2,
    rating: 7.1,
    featured: false,
  },
  {
    slug: 'the-cartographers-daughter',
    title: "The Cartographer's Daughter",
    synopsis:
      'Handed an unfinished map of a coastline that no longer exists, a twelve-year-old sets out to finish it before the survey office demolishes the archive.',
    type: 'movie',
    releaseYear: 2022,
    runtimeMinutes: 108,
    maturityRating: 'U',
    language: 'pt',
    country: 'PT',
    director: 'Rui Salgado',
    cast: ['Ana Beatriz Costa', 'Tomás Pires', 'Inês Alvarenga'],
    tags: ['adventure', 'archive', 'coastline'],
    genres: ['family', 'drama'],
    popularity: 445.7,
    rating: 7.8,
    featured: false,
  },
  {
    slug: 'blackout-protocol',
    title: 'Blackout Protocol',
    synopsis:
      'When the national grid fails for the fourth Tuesday in a row, a load-dispatch engineer realises the outages are spelling something. Six episodes.',
    type: 'series',
    releaseYear: 2025,
    runtimeMinutes: 52,
    maturityRating: 'U/A 16+',
    language: 'en',
    country: 'IN',
    director: 'Arjun Sethi',
    cast: ['Kabir Malhotra', 'Sneha Pillai', 'Rohit Verma', 'Zoya Ahmed'],
    tags: ['infrastructure', 'conspiracy', 'procedural'],
    genres: ['thriller', 'action'],
    popularity: 1655.3,
    rating: 8.2,
    featured: true,
  },
  {
    slug: 'chai-and-circuitry',
    title: 'Chai and Circuitry',
    synopsis:
      'Two repair-shop cousins accept every job they are unqualified for. A comedy about confidence, soldering irons and the customers who trust them anyway.',
    type: 'series',
    releaseYear: 2024,
    runtimeMinutes: 28,
    maturityRating: 'U',
    language: 'hi',
    country: 'IN',
    director: 'Nikhil Bansal',
    cast: ['Tanvi Joshi', 'Imran Sait', 'Bina Chandra'],
    tags: ['workplace', 'sitcom', 'repairs'],
    genres: ['comedy'],
    popularity: 1090.4,
    rating: 8.3,
    featured: false,
  },
  {
    slug: 'ninety-degrees-north',
    title: 'Ninety Degrees North',
    synopsis:
      'Three seasons with the crew who maintain the loneliest weather station on the ice, filmed entirely between resupply flights.',
    type: 'movie',
    releaseYear: 2023,
    runtimeMinutes: 88,
    maturityRating: 'U',
    language: 'no',
    country: 'NO',
    director: 'Kari Sandvik',
    cast: ['Station crew Bravo-7'],
    tags: ['arctic', 'observational', 'weather'],
    genres: ['documentary'],
    popularity: 322.9,
    rating: 8.0,
    featured: false,
  },
  {
    slug: 'the-understudy',
    title: 'The Understudy',
    synopsis:
      'She has performed the role forty times and never once on opening night. Tonight the lead is late, and the stage manager is behaving strangely.',
    type: 'movie',
    releaseYear: 2024,
    runtimeMinutes: 101,
    maturityRating: 'U/A 16+',
    language: 'fr',
    country: 'FR',
    director: 'Camille Aubert',
    cast: ['Élodie Rambert', 'Julien Marchal', 'Sofia Benali'],
    tags: ['theatre', 'ambition', 'twist'],
    genres: ['thriller', 'drama'],
    popularity: 578.6,
    rating: 7.7,
    featured: false,
  },
  {
    slug: 'kite-season',
    title: 'Kite Season',
    synopsis:
      'Every January the rooftops of Ahmedabad turn competitive. For one family it is also the week they must decide whether to sell the house.',
    type: 'movie',
    releaseYear: 2021,
    runtimeMinutes: 113,
    maturityRating: 'U',
    language: 'gu',
    country: 'IN',
    director: 'Hetal Parekh',
    cast: ['Dhruv Shah', 'Kesar Bhatt', 'Nanu Maganlal'],
    tags: ['festival', 'family', 'rooftops'],
    genres: ['family', 'drama'],
    popularity: 398.1,
    rating: 7.9,
    featured: false,
  },
  {
    slug: 'lighthouse-rules',
    title: 'Lighthouse Rules',
    synopsis:
      'Two keepers, one lamp and a rulebook written in 1911 that says nothing about tourists. A comedy of very small stakes taken very seriously.',
    type: 'series',
    releaseYear: 2023,
    runtimeMinutes: 31,
    maturityRating: 'U',
    language: 'en',
    country: 'NZ',
    director: 'Bridget Kahu',
    cast: ['Ed Tamati', 'Wilma Frost'],
    tags: ['two hander', 'island', 'deadpan'],
    genres: ['comedy', 'drama'],
    popularity: 471.2,
    rating: 8.1,
    featured: false,
  },
  {
    slug: 'vault-19',
    title: 'Vault 19',
    synopsis:
      'A retired safe technician is hired to open a vault she designed forty years ago, on the condition that she never asks what is inside.',
    type: 'movie',
    releaseYear: 2025,
    runtimeMinutes: 119,
    maturityRating: 'U/A 16+',
    language: 'de',
    country: 'DE',
    director: 'Ulrike Sommer',
    cast: ['Hanne Vogt', 'Ismail Kaya', 'Bruno Lehmann'],
    tags: ['heist', 'reunion', 'mechanical'],
    genres: ['action', 'thriller'],
    popularity: 1302.7,
    rating: 7.5,
    featured: false,
  },
  {
    slug: 'the-long-now',
    title: 'The Long Now',
    synopsis:
      'The engineers building a clock designed to run for ten thousand years explain, patiently, why the hardest part is the documentation.',
    type: 'movie',
    releaseYear: 2022,
    runtimeMinutes: 79,
    maturityRating: 'U',
    language: 'en',
    country: 'US',
    director: 'Priya Raghavan',
    cast: ['The clock workshop team'],
    tags: ['engineering', 'time', 'craft'],
    genres: ['documentary'],
    popularity: 265.4,
    rating: 8.5,
    featured: false,
  },
  {
    slug: 'anemone',
    title: 'Anemone',
    synopsis:
      'A marine biologist returns to the reef she surveyed as a student and finds it unrecognisable. Forty minutes, no narration, one long dive.',
    type: 'movie',
    releaseYear: 2024,
    runtimeMinutes: 41,
    maturityRating: 'U',
    language: 'en',
    country: 'AU',
    director: 'Joan Mabuiag',
    cast: ['Dr. Alice Pemberton'],
    tags: ['reef', 'short', 'underwater'],
    genres: ['documentary', 'drama'],
    popularity: 188.9,
    rating: 7.3,
    featured: false,
  },
  {
    slug: 'crosswind',
    title: 'Crosswind',
    synopsis:
      'A cargo pilot takes one unlisted passenger across three borders. Neither of them planned for the weather, or for each other.',
    type: 'movie',
    releaseYear: 2023,
    runtimeMinutes: 106,
    maturityRating: 'U/A 13+',
    language: 'es',
    country: 'AR',
    director: 'Mateo Ferrán',
    cast: ['Lucía Ibarra', 'Diego Rentería'],
    tags: ['aviation', 'road movie', 'borders'],
    genres: ['romance', 'thriller'],
    popularity: 826.5,
    rating: 7.2,
    featured: false,
  },
];
