{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: streamflix-secretstore
  namespace: {{ .Values.namespace }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.externalSecrets.secretStoreRegion }}
      auth:
        jwt:
          serviceAccountRef:
            name: streamflix-api
---
{{- range .Values.externalSecrets.sources }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: streamflix-{{ .name }}
  namespace: {{ $.Values.namespace }}
spec:
  refreshInterval: {{ $.Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: streamflix-secretstore
    kind: SecretStore
  target:
    name: streamflix-{{ .name }}
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .remoteRef }}
---
{{- end }}
{{- end }}
