{{- range $component := list "api" "worker" }}
{{- $cfg := index $.Values $component }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: streamflix-{{ $component }}
  namespace: {{ $.Values.namespace }}
  labels:
    {{- include "streamflix.selectorLabels" (dict "component" $component "Values" $.Values) | nindent 4 }}
  {{- if $cfg.serviceAccount.irsaRoleArn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ $cfg.serviceAccount.irsaRoleArn | quote }}
  {{- end }}
---
{{- end }}
